### ISSUE TITLE
Confused about the shorten url thing...

### ISSUE THREAD

**Issue by dk253** [hardillb/wifi-provision#4]
Can you elaborate on this statement?  "then copy it to a public facing http server that supports https and generate a new short URL for this location."

Not sure what you are suggesting me to do.

Thanks!

**Comment by hardillb** [comment]
It should be pretty obvious, the index.html needs to be deployed to a public facing HTTPS server.

The page that holds the interface for configuring the device via Web Bluetooth is advertised via the device as a Eddystone beacon. Given that all lookups for a Eddystone beacon go via a proxy (to prevent lookups being used to track users) the URL needs to public facing.

Pages that use WebBluetooth must be loaded from a trusted source or the sandbox won't allow access to the Bluetooth hardware so it has to be loaded via HTTPS.

The URL needs to be shortened because Eddystone beacons can only advertise up to 17 chars in length.
